//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Testimonial = new HashSet<Testimonial>();
        }
    
        public string reservation_id { get; set; }
        public string customer_name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> reservation_date { get; set; }
        public Nullable<System.TimeSpan> reservation_time { get; set; }
        public Nullable<int> person { get; set; }
        public string menu_id { get; set; }
    
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testimonial> Testimonial { get; set; }
    }
}
