//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public string testimonial_id { get; set; }
        public string content { get; set; }
        public string reservation_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
